name: Build and Release

on:
 workflow_dispatch:
   inputs:
     version:
       description: 'Version number (without v prefix)'
       required: true
       type: string

jobs:
 build:
   name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
   strategy:
     matrix:
       os: [macos-latest, ubuntu-22.04]
       swift: ["6.0"]
       arch: [x86_64, arm64]
       exclude:
         - os: ubuntu-22.04
           arch: arm64
   runs-on: ${{ matrix.os }}

   steps:
   - uses: swift-actions/setup-swift@v2
     with:
       swift-version: ${{ matrix.swift }}
   - uses: actions/checkout@v4
   - name: Build
     run: |
       if [ "${{ matrix.os }}" = "macos-latest" ]; then
         swift build -c release --arch ${{ matrix.arch }}
       else
         swift build -c release
       fi
       tar -czf ${{ github.event.repository.name }}-${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz .build/release/${{ github.event.repository.name }}
   - name: Upload Binary
     uses: actions/upload-artifact@v4
     with:
       name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}
       path: ${{ github.event.repository.name }}-${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

 release:
   needs: build
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Download Artifacts
     uses: actions/download-artifact@v4
   - name: Create Source Archive
     run: |
       git archive --format=tar.gz --output=${{ github.event.repository.name }}-${{ inputs.version }}-src.tar.gz HEAD
   - name: Create Release
     uses: softprops/action-gh-release@v1
     with:
       tag_name: v${{ inputs.version }}
       name: Release v${{ inputs.version }}
       files: |
         ${{ github.event.repository.name }}-${{ inputs.version }}-*
         */*.tar.gz
